[package]
name = "maplibre_native"
version = "0.4.1"
description = "Rust bindings to the MapLibre Native map rendering engine"
authors = ["Yuri Astrakhan <YuriAstrakhan@gmail.com>", "MapLibre contributors"]
repository = "https://github.com/maplibre/maplibre-native-rs"
edition.workspace = true
license.workspace = true
keywords = ["maplibre", "rendering", "gis", "tiles"]
categories = ["external-ffi-bindings", "science::geo", "rendering"]
rust-version = "1.87" # due to cxx
exclude = []

[package.metadata.mln]
repo = "maplibre/maplibre-native"
release = "core-aeaadc06b4e0614f4f243db4dce210c22dde9f9c"

[features]
default = ["log", "pool"] # automatically picks the platform-specific features
metal = [] # default on Apple platforms, do not add to default features
opengl = []
vulkan = []  # default on other platforms
log = ["dep:log"]
pool = ["dep:tokio"]

[dependencies]
cxx.workspace = true
image.workspace = true
log = { workspace = true, optional = true }
thiserror.workspace = true
tokio = { workspace = true, features = ["sync"], optional = true }
url.workspace = true

[build-dependencies]
cmake.workspace = true
cxx-build.workspace = true
downloader.workspace = true
flate2.workspace = true
tar.workspace = true
walkdir.workspace = true
vcpkg.workspace = true

[dev-dependencies]
env_logger.workspace = true
futures.workspace = true
insta = { workspace = true, features = ["json", "redactions"] }
tokio = { workspace = true, features = ["macros", "sync", "rt-multi-thread"] }

[lints]
workspace = true

##########################################################
##########################################################
####  Workspace configuration for the entire project  ####
##########################################################
##########################################################

[workspace]
members = [".", "examples/*"]

[workspace.package]
edition = "2021"
license = "MIT OR Apache-2.0"

[workspace.dependencies]
axum = "0.8"
clap = { version = "4.5.27", features = ["derive", "env", "unstable-markdown"] }
cmake = "0.1"
cxx = "1.0.138"
cxx-build = "1.0.138"
downloader = "0.2.8"
env_logger = "0.11"
flate2 = "1.1.1"
futures = "0.3"
image = "0.25"
insta = "1.43.2"
log = "0.4"
maplibre_native = { path = ".", version = "0.4.1" }
tar = "0.4.44"
thiserror = "2.0.16"
tokio = { version = "1", features = [], default-features = false }
url = "2.5.7"
walkdir = "2.5.0"
vcpkg = "0.2"

[workspace.lints.rust]
missing_debug_implementations = "warn"
missing_docs = "warn"
unused_qualifications = "warn"

[workspace.lints.clippy]
pedantic = { level = "warn", priority = -1 }

# https://insta.rs/docs/quickstart/
[profile.dev.package]
insta.opt-level = 3
similar.opt-level = 3
